export const GET_AUTO_COMPLETE_SUGGESTIONS_LIST = "GET_AUTO_COMPLETE_SUGGESTIONS_LIST";
export const CLEAR_AUTO_COMPLETE_SUGGESTIONS_LIST = "CLEAR_AUTO_COMPLETE_SUGGESTIONS_LIST";
export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS";
export const SHOW_ERROR = "SHOW_ERROR";